### ISSUE TITLE
DARCO - Darstellungsfehler

### ISSUE THREAD

**Issue by hannascholz** [HakunaBanana/otw-bug-tracker#89]
- Symbole ragen in das Videofeld (DE + ENG) 
- auf einem kleinen Bildschirm ist es nicht möglich im Player auf Start, Pause (DE + ENG) 
- Bilder laufen automatisch weiter, FAZIT: Text und bilder passen nicht immer zusammen (DE + ENG)

**Comment by hannascholz** [comment]
![OTW connect_Bild_Text_3](https://user-images.githubusercontent.com/72912195/96274321-a7eeee80-0fd0-11eb-8286-76608afa59d9.jpg)
![OTW connect_Bild_Text_2](https://user-images.githubusercontent.com/72912195/96274326-a8878500-0fd0-11eb-8aef-1193baf89d9b.jpg)
![OTW connect_Bild_Text](https://user-images.githubusercontent.com/72912195/96274330-a9201b80-0fd0-11eb-8fe6-b011e2aca779.jpg)
![OTW connect_Symbole_im_Video](https://user-images.githubusercontent.com/72912195/96274331-a9b8b200-0fd0-11eb-87a2-d68fe84217a5.jpg)
![OTW connect_Downloads_Namen](https://user-images.githubusercontent.com/72912195/96274332-aa514880-0fd0-11eb-8472-4f7005642edc.jpg)

**Comment by HakunaBanana** [comment]
* Symbole ragen in das Videofeld (DE + ENG)                                                                                          => fixed in #2 
* auf einem kleinen Bildschirm ist es nicht möglich im Player auf Start, Pause (DE + ENG)                     => fixed in #28 
* Bilder laufen automatisch weiter, FAZIT: Text und bilder passen nicht immer zusammen (DE + ENG) => ausgelagert nach #90
