### ISSUE TITLE
INTEGRUM 

### ISSUE THREAD

**Issue by hannascholz** [HakunaBanana/otw-bug-tracker#92]
Website von Integrum wird nicht angezeigt/ geladen 

"I spoke with our website administrator and they tell us that they cannot replicate the website issue at their end and indicate that it could be something to do with how your system is communicating with our website. Our certifications are in place. 
 As I am aware, I no longer have access to the portal, so I do not know if this is fixed or not. 
 They asked me to put them in touch with you if the problem still persists. "

**Comment by HakunaBanana** [comment]
Hi Hanna,

i just checked the profile of Integrum the websiteUrls are fine:
https://www.integrum.se for de/en

The problem here is that the certificate of the integrum website is not valid anymore. 
If you want to visit their website you have to accept this warning first:
![image](https://user-images.githubusercontent.com/63208696/96434451-bd009300-1205-11eb-942e-962dcf516180.png)
![image](https://user-images.githubusercontent.com/63208696/96434908-d99ccb00-1205-11eb-91b6-0052a587813a.png)

They have to renew it with the help of their domain provider. In the meantime i change the protocol in this case to http.

Best
Benny

**Comment by HakunaBanana** [comment]
This is not a bug from our side. The customer should fix it asap, this reduces their Google Index Rating and scares a lot of visitors i suppose.

**Comment by hannascholz** [comment]
Danke für die Info. Habe ich an INTEGRUM weitergegeben.

**Comment by HakunaBanana** [comment]
Kein Bug den wir auf unserer Seite beheben können. Deshalb schliesse ich das Ticket
